swipe:
  3:
    left:
      command: 'i3 workspace $(ws-script next)'
    right:
      command: 'i3 workspace $(ws-script prev)'
    up:
      command: exec i3 fullscreen toggle
    down:
      command: exec i3 floating toggle

pinch:
  in:
    command: 'xdotool key ctrl+minus'
  out:
     command: 'xdotool key ctrl+equal'

threshold:
  swipe: 0.4
  pinch: 0.4

interval:
  swipe: 0.8
  pinch: 0.8

